library(testthat)
source('email.R', chdir = TRUE)

test_that("Validación de dirección de correo electrónico", {
  expect_true(str_detect("usuario@example.com", email))
  expect_true(str_detect("us-er.name@domain.co", email))
  expect_true(str_detect("user_name@domain.com", email))
  expect_true(str_detect("user.name@domain.com", email))
  expect_true(str_detect("user.name-1@sub-domain.example.co", email))
  expect_false(str_detect("usuarioexample.com", email))
  expect_false(str_detect("@domain.com", email))
  expect_false(str_detect("usuario@.com", email))
  expect_false(str_detect("usuario@-domain.com", email))
  expect_false(str_detect("usuario@domain-.com", email))
  expect_false(str_detect("usuario@do--main.com", email))
  expect_false(str_detect("usuario@domaincom", email))
  expect_false(str_detect("usuario@domain.c", email))
  expect_false(str_detect("usuario@domain.123", email))
  expect_false(str_detect("usuario@domain.ab_c", email))
  expect_true(str_detect("usuario@sub.domain.example.com", email))
})